name: WIN11-FINAL-STRIKE

on: 
  workflow_dispatch:

jobs:
  windows_beast:
    runs-on: windows-latest
    timeout-minutes: 720 

    steps:
    - name: ربط Tailscale وتفعيل الـ Exit Node
      run: |
        Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe -OutFile tailscale-setup.exe
        Start-Process -FilePath .\tailscale-setup.exe -ArgumentList '/quiet /norestart' -Wait
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --advertise-exit-node

    - name: تفعيل الـ RDP والسيطرة على حساب المسؤول
      run: |
        # تفعيل البروتوكول وتجاوز جدار الحماية
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        # تغيير كلمة سر المسؤول الحالي (تجنب إنشاء حساب جديد)
        $admin = "runneradmin"
        net user $admin Sniper@2026

    - name: بروتوكول البقاء لـ 12 ساعة
      run: |
        $i = 0
        while($i -lt 720) {
          Write-Host "السيرفر في حالة تشغيل كاملة.. دقيقة رقم: $i"
          Start-Sleep -Seconds 60
          $i++
        }
        
